<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Playlist add</title>
</head>
<body>
    <form action="index.php?c=playlist" method="post">
        <label for="titulo">Titulo Playlist:</label>
        <input type="text" name="name">
        <input type="submit" name="addPlaylist" value="Crear">
    </form>
</body>
</html>