<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Añadir Canción</title>
</head>
<body>
    <h1>Añadir Canción</h1>
    <form method="POST" action="index.php?c=song" enctype="multipart/form-data">
        <label for="titulo">Titulo:</label>
        <input type="text" name="title" required>
        <label for="author">Artista:</label>
        <input type="text" name="author" required>
        <label for="duracion">Duración:</label>
        <input type="text" name="duration" required>
        <label for="imagen">Imagen:</label>
        <input type="file" name="img" required/>
        <label for="ruta">Archivo:</label>
        <input type="file" name="file">

        <!-- Otros campos relevantes -->
        <input type="submit" name="addSong" value="Añadir Canción">
    </form>
</body>
</html>
