<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>

<body>
    <h2>Editar playlist</h2>
    <form method="post" action="index.php?c=playlist">
        <input type="text" name="song" placeholder="Buscar canción..." />
        <input type="submit" name="searchSong" value="Buscar">

    </form>

    <?php
    // var_dump( $resultSearch);
    //var_dump($resultSearch);
    // var_dump($resultSearch->getImg());
    if (!empty($resultSearch)) {
        foreach ($resultSearch as $song) {
            echo '<ul>
                     <li>';
            echo '       <img src="public/img/' . $song->getImg() . '"> Titulo: ' . $song->getTitle() . ' Autor: ' . $song->getAuthor() . ' Duracion: ' . $song->getDuration() . ' 
                            <a href="">Añadir a playlist</a>
                     </li> 
                  </ul>';
        }
    } ?>
</body>

</html>