<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/water.css@2/out/water.css">
    <title>Document</title>
</head>

<body>
    <h2>Editar playlist</h2>
    <form method="post" action="index.php?c=playlist">
        <input type="text" name="song" placeholder="Buscar canción..." />
        <datalist id="songList">
            <?php
            // En construccion....
            if (!empty($resultSearch)) {
                foreach ($resultSearch as $song) {
                    echo '<option value="' . $song->getTitle() . '">';
                }
            }
           
            ?>
        </datalist>
        <input type="submit" name="searchSong" value="Buscar">

    </form>
    <?php
     echo '<a href="index.php"><button>Volver...</button></a>';
    //var_dump( $resultSearch);
    //var_dump($resultSearch);
    // var_dump($resultSearch->getImg());
    //echo $_SESSION['playListId'];
    if (!empty($resultSearch)) {
        foreach ($resultSearch as $song) {
            //$sonId = $song->getId();
            //var_dump($song);
            echo '<ul>
                     <li>';
            echo '       <img src="public/img/' . $song->getImg() . '" style="width:30px"> Titulo: ' .      $song->getTitle() . ' Autor: ' . $song->getAuthor() . ' Duracion: ' . $song->getDuration() . ' 
                    <a href="index.php?c=playlist&addSongPlaylist=1&songId='.$song->getId().'&playListId='.$_SESSION['playListId'].'">Añadir a playlist</a>
                 </li> 
            </ul>';
        }
    } ?>

</body>

</html>