<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Login</title>
</head>
<body>
  <h1>Bienvenido, Logueate!</h1>
<form method="POST" action="index.php?c=user">
      User
      <input type="text" name="usuario" required>
      Password
      <input type="password" name="password" required>
      <input type="submit" name="login" value="Entrar">
    </form>
</body>
</html>