<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <?php
    if(!empty($_SESSION['user'])){

    
    ?>
    <h1>Estás logueado</h1>
    <form method="POST" action="index.php?c=user">
        <input type="submit" name="logout" value="Cerrar Sesión">
    </form>
    <?php } ?>
    <?php 
        if(!empty($_SESSION['user']) && $_SESSION['user']->getRol() > 0){
    ?>
    <a href="index.php?c=song&addSong=1">Añadir una Canción</a>
    <a href="index.php?c=playlist&addPlaylist=1">Añadir una playlist</a>
    <br>
    <?php } ?>
    

</body>
</html>
