<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <?php
        if($_SESSION['user']->getRol() < 1){

        
    ?>
    <h1>Bienvenido Usuario sin registrar</h1>
    <?php
        }
    ?>
    <?php
        if($_SESSION['user']->getRol() > 0){
    ?>
    <h1>Bienvenido usuario registrado</h1>
    <?php } ?>
</body>
</html>