<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/water.css@2/out/water.css">
  <title>Registro</title>
</head>
<body>
  
<h1>Bienvenido Usuario sin registrar</h1>
    <form method="POST" action="index.php?c=user">
      User
      <input type="text" name="usuario" required>
      Password
      <input type="password" name="password" required>
      <input type="submit" name="register" value="Registrar">
    </form>
</body>
</html>