controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

app_pokemon_add:
    path: '/pokemon/add/{id}'
    controller: 'App\Controller\PokemonController::add'