<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Login en web de pelis</title>
</head>
<body>
<h2>Logeo</h2>
    <form action="index.php?login" method="post">
        <input type="text" name="user" placeholder="Usuario"/>
        <input type="password" name="password" placeholder="Contraseña"/>
        <input type="submit" name="logeo" value="Entrar"/>
    </form>

    <h2>Registro</h2>
    <form action="index.php?login" method="post">
        <input type="text" name="user" placeholder="Usuario"/>
        <input type="password" name="password" placeholder="Contraseña"/>
        <input type="password" name="password2" placeholder="Repite la contraseña"/>
        <input type="submit" name="registro" value="Registro"/>
    </form>
</body>
</html>