<?php
// Asegúrate de incluir las clases y archivos necesarios aquí

if(isset($_SESSION['editPubId'])) {
    $editPubId = $_SESSION['editPubId'];
    // Recupera la información de la publicación que se va a editar
    $pubToEdit = PublicacionRepository::getPubById($editPubId);
}
?>

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Editar Publicación</title>
</head>
<body>
    <h2>Editar Publicación</h2>

    <form action="index.php?c=pub" method="POST" enctype="multipart/form-data">
        <input type="text" name="title" placeholder="Título" value="<?php echo $pubToEdit->getTitle(); ?>"><br><br>
        <textarea name="text" cols="30" rows="10"><?php echo $pubToEdit->getText(); ?></textarea><br><br>
        <input type="file" name="img" />
        <!-- Incluye un campo oculto para el ID de la publicación -->
        <input type="hidden" name="editPubId" value="<?php echo $pubToEdit->getId(); ?>">
        <input type="submit" name="editPub" value="Guardar Cambios">
    </form>
</body>
</html>
