<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>

<body>
    <form action="index.php" method="POST">
        <input type="text" name="title" value="Title">
        <input type="text" name="text" value="Text">
        <input type="submit" name="enviarPub" value="Enviar">
    </form>
</body>

</html>