<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>

<body>
    <!-- enctype sirve para que puedas enviar archivos -->
    <form action="index.php" method="POST" enctype="multipart/form-data">
        <input type="text" name="title" placeholder="Titulo"><br><br>
        <textarea name="text" id="" cols="30" rows="10"></textarea><br><br>
        <input type="file" name="img" />
        <input type="submit" name="newPub" value="Enviar">
    </form>
</body>

</html>