/**
 * AEMET OpenData
 * AEMET OpenData es una API REST desarrollado por AEMET que permite la difusión y la reutilización de la información meteorológica y climatológica de la Agencia, en el sentido indicado en la Ley 18/2015, de 9 de julio, por la que se modifica la Ley 37/2007, de 16 de noviembre, sobre reutilización de la información del sector público. (IMPORTANTE: Para poder realizar peticiones, es necesario introducir en API Key haciendo clic en el círculo rojo de recurso REST).
 *
 * OpenAPI spec version: 2.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.0
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/Model200', 'model/Model401', 'model/Model404', 'model/Model429'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('../model/Model200'), require('../model/Model401'), require('../model/Model404'), require('../model/Model429'));
  } else {
    // Browser globals (root is window)
    if (!root.AemetOpenData) {
      root.AemetOpenData = {};
    }
    root.AemetOpenData.AvisosCapApi = factory(root.AemetOpenData.ApiClient, root.AemetOpenData.Model200, root.AemetOpenData.Model401, root.AemetOpenData.Model404, root.AemetOpenData.Model429);
  }
}(this, function(ApiClient, Model200, Model401, Model404, Model429) {
  'use strict';

  /**
   * AvisosCap service.
   * @module api/AvisosCapApi
   * @version 2.0
   */

  /**
   * Constructs a new AvisosCapApi. 
   * @alias module:api/AvisosCapApi
   * @class
   * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
   * default to {@link module:ApiClient#instance} if unspecified.
   */
  var exports = function(apiClient) {
    this.apiClient = apiClient || ApiClient.instance;


    /**
     * Callback function to receive the result of the avisosDeFenmenosMeteorolgicosAdversosArchivo operation.
     * @callback module:api/AvisosCapApi~avisosDeFenmenosMeteorolgicosAdversosArchivoCallback
     * @param {String} error Error message, if any.
     * @param {module:model/Model200} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Avisos de Fenómenos Meteorológicos Adversos. Archivo.
     *  Avisos de Fenómenos Meteorológicos adversos para el rango de fechas seleccionado (datos desde 18/06/2018).
     * @param {String} fechaIniStr Fecha Inicial (AAAA-MM-DDTHH:MM:SSUTC)
     * @param {String} fechaFinStr Fecha Final (AAAA-MM-DDTHH:MM:SSUTC)
     * @param {module:api/AvisosCapApi~avisosDeFenmenosMeteorolgicosAdversosArchivoCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/Model200}
     */
    this.avisosDeFenmenosMeteorolgicosAdversosArchivo = function(fechaIniStr, fechaFinStr, callback) {
      var postBody = null;

      // verify the required parameter 'fechaIniStr' is set
      if (fechaIniStr === undefined || fechaIniStr === null) {
        throw new Error("Missing the required parameter 'fechaIniStr' when calling avisosDeFenmenosMeteorolgicosAdversosArchivo");
      }

      // verify the required parameter 'fechaFinStr' is set
      if (fechaFinStr === undefined || fechaFinStr === null) {
        throw new Error("Missing the required parameter 'fechaFinStr' when calling avisosDeFenmenosMeteorolgicosAdversosArchivo");
      }


      var pathParams = {
        'fechaIniStr': fechaIniStr,
        'fechaFinStr': fechaFinStr
      };
      var queryParams = {
      };
      var collectionQueryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = ['api_key'];
      var contentTypes = ['application/json'];
      var accepts = ['application/json'];
      var returnType = Model200;

      return this.apiClient.callApi(
        '/api/avisos_cap/archivo/fechaini/{fechaIniStr}/fechafin/{fechaFinStr}', 'GET',
        pathParams, queryParams, collectionQueryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

    /**
     * Callback function to receive the result of the avisosDeFenmenosMeteorolgicosAdversosLtimo_ operation.
     * @callback module:api/AvisosCapApi~avisosDeFenmenosMeteorolgicosAdversosLtimo_Callback
     * @param {String} error Error message, if any.
     * @param {module:model/Model200} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Avisos de Fenómenos Meteorológicos Adversos. Último.
     *  Últimos Avisos de Fenómenos Meteorológicos adversos elaborado para el área seleccionada.
     * @param {String} area  | Código | Área | |----------|----------| | esp  | España| | 61  | Andalucía   | | 62  | Aragón   | | 63  | Asturias, Principado de  | | 64  | Ballears, Illes   | | 78  | Ceuta   | | 65  | Canarias   | | 66  | Cantabria   | | 67  | Castilla y León   | | 68  | Castilla - La Mancha   | | 69  | Cataluña   | | 77  | Comunitat Valenciana   | | 70  | Extremadura   | | 71  | Galicia   | | 72  | Madrid, Comunidad de    | | 79  | Melilla   | | 73  | Murcia, Región de   | | 74  | Navarra, Comunidad Foral de   | | 75  | País Vasco | | 76  | Rioja, La
     * @param {module:api/AvisosCapApi~avisosDeFenmenosMeteorolgicosAdversosLtimo_Callback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/Model200}
     */
    this.avisosDeFenmenosMeteorolgicosAdversosLtimo_ = function(area, callback) {
      var postBody = null;

      // verify the required parameter 'area' is set
      if (area === undefined || area === null) {
        throw new Error("Missing the required parameter 'area' when calling avisosDeFenmenosMeteorolgicosAdversosLtimo_");
      }


      var pathParams = {
        'area': area
      };
      var queryParams = {
      };
      var collectionQueryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = ['api_key'];
      var contentTypes = ['application/json'];
      var accepts = ['application/json'];
      var returnType = Model200;

      return this.apiClient.callApi(
        '/api/avisos_cap/ultimoelaborado/area/{area}', 'GET',
        pathParams, queryParams, collectionQueryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }
  };

  return exports;
}));
