<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/water.css@2/out/water.css">
    <title>Administración de Roles</title>
</head>

<body>
    <h1>Panel de administración</h1>
    <a href="index.php"><button>Volver</button></a>
    <div class="roles">
        
        <?php
        if (!empty($_SESSION['user']) && !empty($users)) { 
            foreach ($users as $user) {
            ?>
        <form method="post" action="index.php?c=admin">
            <strong>Usuario:</strong><?php echo $user->getName(); ?><strong> Rol: </strong><?php echo $user->getRol();?>
            <input type="hidden" name="userId" value="<?php echo $user->getId(); ?>">
            <select name="newRole" id="">
                <option value="1">Usuario Normal</option>
                <option value="2">Usuario Administrador</option>
                <option value="0">Banear Usuario</option>
            </select>
            <input type="submit" name="changeRole" value="Cambiar Rol">
        </form>
        <?php
        }
    }?>

    </div>

</body>

</html>