/**
 * AEMET OpenData
 * AEMET OpenData es una API REST desarrollado por AEMET que permite la difusión y la reutilización de la información meteorológica y climatológica de la Agencia, en el sentido indicado en la Ley 18/2015, de 9 de julio, por la que se modifica la Ley 37/2007, de 16 de noviembre, sobre reutilización de la información del sector público. (IMPORTANTE: Para poder realizar peticiones, es necesario introducir en API Key haciendo clic en el círculo rojo de recurso REST).
 *
 * OpenAPI spec version: 2.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.0
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.AemetOpenData) {
      root.AemetOpenData = {};
    }
    root.AemetOpenData.Model200 = factory(root.AemetOpenData.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';




  /**
   * The Model200 model module.
   * @module model/Model200
   * @version 2.0
   */

  /**
   * Constructs a new <code>Model200</code>.
   * @alias module:model/Model200
   * @class
   * @param descripcion {String} 
   * @param estado {Number} 
   * @param datos {String} 
   * @param metadatos {String} 
   */
  var exports = function(descripcion, estado, datos, metadatos) {
    var _this = this;

    _this['descripcion'] = descripcion;
    _this['estado'] = estado;
    _this['datos'] = datos;
    _this['metadatos'] = metadatos;
  };

  /**
   * Constructs a <code>Model200</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/Model200} obj Optional instance to populate.
   * @return {module:model/Model200} The populated <code>Model200</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('descripcion')) {
        obj['descripcion'] = ApiClient.convertToType(data['descripcion'], 'String');
      }
      if (data.hasOwnProperty('estado')) {
        obj['estado'] = ApiClient.convertToType(data['estado'], 'Number');
      }
      if (data.hasOwnProperty('datos')) {
        obj['datos'] = ApiClient.convertToType(data['datos'], 'String');
      }
      if (data.hasOwnProperty('metadatos')) {
        obj['metadatos'] = ApiClient.convertToType(data['metadatos'], 'String');
      }
    }
    return obj;
  }

  /**
   * @member {String} descripcion
   * @default 'Éxito'
   */
  exports.prototype['descripcion'] = 'Éxito';
  /**
   * @member {Number} estado
   */
  exports.prototype['estado'] = undefined;
  /**
   * @member {String} datos
   */
  exports.prototype['datos'] = undefined;
  /**
   * @member {String} metadatos
   */
  exports.prototype['metadatos'] = undefined;



  return exports;
}));


