<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>main</title>
</head>

<body>
    <h1>Publicaciones</h1>

    <?php
    foreach ($pubs as $pub) {
        echo $pub->getText() . "<br>";
    }
    ?>

    <form method="POST" action="index.php">
        <br>
        User
        <input type="text" name="usuario" required><br>
        Password
        <input type="password" name="password" required><br>
        <input type="submit" name="login" value="Entrar">
    </form>
    <?php
    if (!empty($_SESSION['user'])) {
        echo "Es correcto<br>";
        echo "<a href='index.php?newpub=1'>Publicar</a>";
    } else {
        echo "No es correcto<br>";
        echo "Inicia sesion para publicar";
    }
    ?>

</body>

</html>