version: '3.7'
services:
  node-red:
    build: .
    container_name: "node-red"
    environment:
      TZ: ${TZ}
    image: "nodered/node-red"
    restart: unless-stopped
    ports:
      - "1880:1880"
    volumes:
      - "data:/data"
volumes:
  data:
    name: node-red_data
    driver: local-persist
    driver_opts:
      mountpoint: ${LOCAL_PERSIST}/node-red/data