/**
 * AEMET OpenData
 * AEMET OpenData es una API REST desarrollado por AEMET que permite la difusión y la reutilización de la información meteorológica y climatológica de la Agencia, en el sentido indicado en la Ley 18/2015, de 9 de julio, por la que se modifica la Ley 37/2007, de 16 de noviembre, sobre reutilización de la información del sector público. (IMPORTANTE: Para poder realizar peticiones, es necesario introducir en API Key haciendo clic en el círculo rojo de recurso REST).
 *
 * OpenAPI spec version: 2.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.0
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.AemetOpenData);
  }
}(this, function(expect, AemetOpenData) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new AemetOpenData.PrediccionesNormalizadasTextoApi();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('PrediccionesNormalizadasTextoApi', function() {
    describe('prediccinCCAAHoyArchivo_', function() {
      it('should call prediccinCCAAHoyArchivo_ successfully', function(done) {
        //uncomment below and update the code to test prediccinCCAAHoyArchivo_
        //instance.prediccinCCAAHoyArchivo_(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('prediccinCCAAHoyTiempoActual_', function() {
      it('should call prediccinCCAAHoyTiempoActual_ successfully', function(done) {
        //uncomment below and update the code to test prediccinCCAAHoyTiempoActual_
        //instance.prediccinCCAAHoyTiempoActual_(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('prediccinCCAAMaanaArchivo_', function() {
      it('should call prediccinCCAAMaanaArchivo_ successfully', function(done) {
        //uncomment below and update the code to test prediccinCCAAMaanaArchivo_
        //instance.prediccinCCAAMaanaArchivo_(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('prediccinCCAAMaanaTiempoActual_', function() {
      it('should call prediccinCCAAMaanaTiempoActual_ successfully', function(done) {
        //uncomment below and update the code to test prediccinCCAAMaanaTiempoActual_
        //instance.prediccinCCAAMaanaTiempoActual_(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('prediccinCCAAMedioPlazoArchivo_', function() {
      it('should call prediccinCCAAMedioPlazoArchivo_ successfully', function(done) {
        //uncomment below and update the code to test prediccinCCAAMedioPlazoArchivo_
        //instance.prediccinCCAAMedioPlazoArchivo_(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('prediccinCCAAMedioPlazoTiempoActual_', function() {
      it('should call prediccinCCAAMedioPlazoTiempoActual_ successfully', function(done) {
        //uncomment below and update the code to test prediccinCCAAMedioPlazoTiempoActual_
        //instance.prediccinCCAAMedioPlazoTiempoActual_(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('prediccinCCAAPasadoMaanaArchivo_', function() {
      it('should call prediccinCCAAPasadoMaanaArchivo_ successfully', function(done) {
        //uncomment below and update the code to test prediccinCCAAPasadoMaanaArchivo_
        //instance.prediccinCCAAPasadoMaanaArchivo_(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('prediccinCCAAPasadoMaanaTiempoActual_', function() {
      it('should call prediccinCCAAPasadoMaanaTiempoActual_ successfully', function(done) {
        //uncomment below and update the code to test prediccinCCAAPasadoMaanaTiempoActual_
        //instance.prediccinCCAAPasadoMaanaTiempoActual_(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('prediccinNacionalHoyArchivo_', function() {
      it('should call prediccinNacionalHoyArchivo_ successfully', function(done) {
        //uncomment below and update the code to test prediccinNacionalHoyArchivo_
        //instance.prediccinNacionalHoyArchivo_(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('prediccinNacionalHoyTiempoActual_', function() {
      it('should call prediccinNacionalHoyTiempoActual_ successfully', function(done) {
        //uncomment below and update the code to test prediccinNacionalHoyTiempoActual_
        //instance.prediccinNacionalHoyTiempoActual_(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('prediccinNacionalMaanaArchivo_', function() {
      it('should call prediccinNacionalMaanaArchivo_ successfully', function(done) {
        //uncomment below and update the code to test prediccinNacionalMaanaArchivo_
        //instance.prediccinNacionalMaanaArchivo_(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('prediccinNacionalMaanaTiempoActual_', function() {
      it('should call prediccinNacionalMaanaTiempoActual_ successfully', function(done) {
        //uncomment below and update the code to test prediccinNacionalMaanaTiempoActual_
        //instance.prediccinNacionalMaanaTiempoActual_(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('prediccinNacionalMedioPlazoArchivo_', function() {
      it('should call prediccinNacionalMedioPlazoArchivo_ successfully', function(done) {
        //uncomment below and update the code to test prediccinNacionalMedioPlazoArchivo_
        //instance.prediccinNacionalMedioPlazoArchivo_(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('prediccinNacionalMedioPlazoTiempoActual_', function() {
      it('should call prediccinNacionalMedioPlazoTiempoActual_ successfully', function(done) {
        //uncomment below and update the code to test prediccinNacionalMedioPlazoTiempoActual_
        //instance.prediccinNacionalMedioPlazoTiempoActual_(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('prediccinNacionalPasadoMaanaArchivo_', function() {
      it('should call prediccinNacionalPasadoMaanaArchivo_ successfully', function(done) {
        //uncomment below and update the code to test prediccinNacionalPasadoMaanaArchivo_
        //instance.prediccinNacionalPasadoMaanaArchivo_(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('prediccinNacionalPasadoMaanaTiempoActual_', function() {
      it('should call prediccinNacionalPasadoMaanaTiempoActual_ successfully', function(done) {
        //uncomment below and update the code to test prediccinNacionalPasadoMaanaTiempoActual_
        //instance.prediccinNacionalPasadoMaanaTiempoActual_(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('prediccinNacionalTendenciaArchivo_', function() {
      it('should call prediccinNacionalTendenciaArchivo_ successfully', function(done) {
        //uncomment below and update the code to test prediccinNacionalTendenciaArchivo_
        //instance.prediccinNacionalTendenciaArchivo_(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('prediccinNacionalTendenciaTiempoActual_', function() {
      it('should call prediccinNacionalTendenciaTiempoActual_ successfully', function(done) {
        //uncomment below and update the code to test prediccinNacionalTendenciaTiempoActual_
        //instance.prediccinNacionalTendenciaTiempoActual_(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('prediccinProvinciaHoyArchivo_', function() {
      it('should call prediccinProvinciaHoyArchivo_ successfully', function(done) {
        //uncomment below and update the code to test prediccinProvinciaHoyArchivo_
        //instance.prediccinProvinciaHoyArchivo_(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('prediccinProvinciaHoyTiempoActual_', function() {
      it('should call prediccinProvinciaHoyTiempoActual_ successfully', function(done) {
        //uncomment below and update the code to test prediccinProvinciaHoyTiempoActual_
        //instance.prediccinProvinciaHoyTiempoActual_(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('prediccinProvinciaMaanaArchivo_', function() {
      it('should call prediccinProvinciaMaanaArchivo_ successfully', function(done) {
        //uncomment below and update the code to test prediccinProvinciaMaanaArchivo_
        //instance.prediccinProvinciaMaanaArchivo_(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('prediccinProvinciaMaanaTiempoActual_', function() {
      it('should call prediccinProvinciaMaanaTiempoActual_ successfully', function(done) {
        //uncomment below and update the code to test prediccinProvinciaMaanaTiempoActual_
        //instance.prediccinProvinciaMaanaTiempoActual_(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
  });

}));
